[package]
name = "wakeonrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clearscreen = "3.0.0"
ctrlc = "3.4.4"
gethostname = "0.4.3"
mac_address = "1.1.6"
serde = "1.0.198"
