name: wakeonrust

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - default
    stdin_open: true
    tty: true
    develop:
      watch:
        - action: rebuild
          path: .
    deploy:
      mode: replicated
      replicas: 3


networks:
  default:
    driver: bridge