name: wakeonrust

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - default
    stdin_open: true
    tty: true
    develop:
      watch:
        - action: rebuild
          path: .
    deploy:
      mode: replicated
      replicas: 2

  manager:
    extends:
      service: client
    command: [
      "cargo",
      "run", 
      # "manager"
    ]
    deploy:
      mode: replicated
      replicas: 1


networks:
  default:
    driver: bridge